swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <form><math><h1 onbegin="alert('XSS1')" onClick="alert('XSS')">BU0</h1>">

  version: production
basePath: /test-c4sper0
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
