swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <form><math>'>"<svg onload="document.write('test')"><h1 onclick="prompt('XSS')">BU0</h1></math></form><img/src="x" on%65rror=confirm(1)>

  version: production
basePath: /test-c4sper0
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
